#!/usr/bin/env python3
"""Build one static browser payload per Spanish Congress election.

The Ministry of the Interior publishes a consolidated workbook containing final
province-level participation, candidacy votes and seat allocations for every
Congress election since 1977. The three existing elections are reviewed assets
and are deliberately not regenerated by this script.
"""

from __future__ import annotations

import argparse
import hashlib
import json
import random
import re
import unicodedata
from collections import Counter, defaultdict, deque
from pathlib import Path

import pandas as pd
from generate_geographic_layout import generate_layout


CURRENT_ELECTIONS = {"2023-07-23", "2019-11-10", "2019-04-28"}
SOURCE_URL = "https://descargas.interior.gob.es/datasets/resultados_electorales/Elecciones-Congreso.xlsx"
NEIGHBORS = ((1, 0), (1, -1), (0, -1), (-1, 0), (-1, 1), (0, 1))

REGION_BY_PROVINCE = {
    "01": "16", "02": "08", "03": "10", "04": "01", "05": "07", "06": "11",
    "07": "04", "08": "09", "09": "07", "10": "11", "11": "01", "12": "10",
    "13": "08", "14": "01", "15": "12", "16": "08", "17": "09", "18": "01",
    "19": "08", "20": "16", "21": "01", "22": "02", "23": "01", "24": "07",
    "25": "09", "26": "17", "27": "12", "28": "13", "29": "01", "30": "14",
    "31": "15", "32": "12", "33": "03", "34": "07", "35": "05", "36": "12",
    "37": "07", "38": "05", "39": "06", "40": "07", "41": "01", "42": "07",
    "43": "09", "44": "02", "45": "08", "46": "10", "47": "07", "48": "16",
    "49": "07", "50": "02", "51": "18", "52": "19",
}

REGION_NAMES_EN = {
    "01": "Andalusia", "02": "Aragon", "03": "Asturias", "04": "Balearic Islands",
    "05": "Canary Islands", "06": "Cantabria", "07": "Castile and León",
    "08": "Castile-La Mancha", "09": "Catalonia", "10": "Valencian Community",
    "11": "Extremadura", "12": "Galicia", "13": "Community of Madrid",
    "14": "Region of Murcia", "15": "Navarre", "16": "Basque Country",
    "17": "La Rioja", "18": "Ceuta", "19": "Melilla",
}
REGION_NAMES_ES = {
    "01": "Andalucía", "02": "Aragón", "03": "Principado de Asturias",
    "04": "Illes Balears", "05": "Canarias", "06": "Cantabria",
    "07": "Castilla y León", "08": "Castilla-La Mancha", "09": "Cataluña",
    "10": "Comunitat Valenciana", "11": "Extremadura", "12": "Galicia",
    "13": "Comunidad de Madrid", "14": "Región de Murcia",
    "15": "Comunidad Foral de Navarra", "16": "País Vasco", "17": "La Rioja",
    "18": "Ceuta", "19": "Melilla",
}

# IDs are reused only for recognizable party families. Electoral coalitions with
# materially different identities keep their own IDs and aliases.
PARTIES = {
    "PSOE": ("PSOE", "Partido Socialista Obrero Español", "#e34b4b"),
    "PP": ("PP", "Partido Popular", "#2f6fa7"),
    "AP": ("AP / CP", "Alianza Popular / Coalición Popular", "#4b6f91"),
    "UCD": ("UCD", "Unión de Centro Democrático", "#5aa6a1"),
    "PCE": ("PCE", "Partido Comunista de España", "#b53b32"),
    "IU": ("IU", "Izquierda Unida", "#a83232"),
    "CDS": ("CDS", "Centro Democrático y Social", "#61a9a2"),
    "UP": ("Podemos–IU", "Podemos, Izquierda Unida and confluences", "#7657a6"),
    "SUMAR": ("SUMAR", "Sumar", "#d75c9f"),
    "VOX": ("VOX", "Vox", "#63a84f"),
    "CS": ("Cs", "Ciudadanos", "#ef8c3f"),
    "CIU": ("CiU", "Convergència i Unió", "#c99b2d"),
    "CDC": ("CDC", "Convergència Democràtica de Catalunya", "#39a8a2"),
    "DL": ("DL", "Democràcia i Llibertat", "#39a8a2"),
    "JUNTS": ("Junts", "Junts per Catalunya", "#28a5a0"),
    "ERC": ("ERC", "Esquerra Republicana de Catalunya", "#e8bd3f"),
    "PNV": ("EAJ-PNV", "Euzko Alderdi Jeltzalea–Partido Nacionalista Vasco", "#4f9b68"),
    "HB": ("HB", "Herri Batasuna", "#6d923e"),
    "EHB": ("EH Bildu", "Euskal Herria Bildu", "#83ad47"),
    "EA": ("EA", "Eusko Alkartasuna", "#7a9d67"),
    "EE": ("EE", "Euskadiko Ezkerra", "#bf4d4d"),
    "BNG": ("BNG", "Bloque Nacionalista Galego", "#69a6c6"),
    "CC": ("CCa", "Coalición Canaria", "#e9ad36"),
    "UPN": ("UPN", "Unión del Pueblo Navarro", "#2674a9"),
    "PA": ("PA", "Partido Andalucista", "#4f9f73"),
    "PAR": ("PAR", "Partido Aragonés", "#d9a62e"),
    "UV": ("UV", "Unió Valenciana", "#5687bd"),
    "CHA": ("CHA", "Chunta Aragonesista", "#7f9f43"),
    "UPYD": ("UPyD", "Unión Progreso y Democracia", "#d95791"),
    "AMAIUR": ("Amaiur", "Amaiur", "#6b943c"),
    "COMPROMIS": ("Compromís", "Compromís", "#d58c2f"),
    "GBAI": ("Geroa Bai", "Geroa Bai", "#6e9860"),
    "FAC": ("FAC", "Foro de Ciudadanos", "#306ea4"),
}
FALLBACK_COLORS = ("#7d6b91", "#b06f52", "#567f84", "#8b8752", "#9b5f71", "#57749b", "#6e8b62", "#a56f32", "#805e48", "#6c7188", "#78908d", "#927660")


def normalized(value: str) -> str:
    value = unicodedata.normalize("NFKD", str(value)).encode("ascii", "ignore").decode()
    return re.sub(r"[^a-z0-9]+", "", value.lower())


def party_family(name: str, election_id: str) -> str:
    n = normalized(name)
    if "psoe" in n or "partidosocialistaobrero" in n or "partitdelssocialistes" in n or "partidosocialistadeeuskadi" in n: return "PSOE"
    if "uniondelpueblonavarro" in n: return "UPN"
    if "partidopopular" in n or "partitpopular" in n or n.startswith("ppencoalicion"): return "PP"
    if "alianzapop" in n or "coalicionpopular" in n or "coaliciondemocratica" in n or n.endswith("ccap"): return "AP"
    if "uniondecentrodemocratico" in n or "centristesdecatalunya" in n: return "UCD"
    if "centrodemocraticoysocial" in n or "centredemocraticisocial" in n: return "CDS"
    if "partidocomunista" in n or "psucpce" in n: return "PCE"
    if election_id >= "1986" and any(x in n for x in ("izquierdaunida", "esquerraunida", "izquierdaxunida")): return "IU"
    if election_id in {"2015-12-20", "2016-06-26"} and any(x in n for x in ("podemos", "encomu", "enmarea")): return "UP"
    if "sumar" in n: return "SUMAR"
    if n.startswith("vox"): return "VOX"
    if "forodeciudadanos" in n: return "FAC"
    if "ciudadanos" in n or "ciutadans" in n: return "CS"
    if "convergencia" in n and "unio" in n: return "CIU"
    if "convergenciademocratica" in n: return "CDC"
    if "democraciaillibertat" in n: return "DL"
    if "junts" in n: return "JUNTS"
    if "esquerrarepublicana" in n: return "ERC"
    if "partidonacionalistavasco" in n or "eajpnv" in n: return "PNV"
    if "herribatasuna" in n: return "HB"
    if "euskalherriabildu" in n or "ehbildu" in n: return "EHB"
    if "euskoalkartasuna" in n: return "EA"
    if "euskadiko" in n and "ezkerra" in n: return "EE"
    if "bloquenacionalistagalego" in n: return "BNG"
    if "coalicioncanaria" in n or "agrupacionesindependientesdecanarias" in n: return "CC"
    if "partidoandalucista" in n: return "PA"
    if "partidoaragones" in n: return "PAR"
    if "uniovalenciana" in n: return "UV"
    if "chuntaaragonesista" in n: return "CHA"
    if "unionprogresoydemocracia" in n: return "UPYD"
    if "amaiur" in n: return "AMAIUR"
    if "compromis" in n and "podemos" not in n: return "COMPROMIS"
    if "geroabai" in n: return "GBAI"
    short = name.rsplit(" - ", 1)[-1].strip()[:28]
    digest = hashlib.sha1(name.encode("utf-8")).hexdigest()[:7]
    return f"OTHER-{normalized(short)[:20] or 'party'}-{digest}"


def party_meta(party_id: str, aliases: set[str]) -> dict:
    if party_id in PARTIES:
        short, name, color = PARTIES[party_id]
    else:
        preferred = min(aliases, key=lambda value: (len(value), value))
        short = preferred.rsplit(" - ", 1)[-1].strip()[:28]
        name = preferred
        color = FALLBACK_COLORS[int(hashlib.sha1(party_id.encode()).hexdigest()[:4], 16) % len(FALLBACK_COLORS)]
    return {"id": party_id, "short": short, "name": {"en": name, "es": name}, "color": color, "aliases": sorted(aliases)}


def connected(nodes: set[tuple[int, int]]) -> bool:
    if not nodes: return True
    seen = {next(iter(nodes))}; queue = deque(seen)
    while queue:
        q, r = queue.popleft()
        for dq, dr in NEIGHBORS:
            nxt = (q + dq, r + dr)
            if nxt in nodes and nxt not in seen: seen.add(nxt); queue.append(nxt)
    return len(seen) == len(nodes)


def province_graph(cells: list[dict]) -> dict[str, set[str]]:
    lookup = {(cell["q"], cell["r"]): cell["provinceId"] for cell in cells}; graph = defaultdict(set)
    for (q, r), pid in lookup.items():
        for dq, dr in NEIGHBORS:
            other = lookup.get((q + dq, r + dr))
            if other and other != pid: graph[pid].add(other); graph[other].add(pid)
    return graph


def shortest_path(graph: dict[str, set[str]], source: str, destination: str) -> list[str] | None:
    queue = deque([[source]]); seen = {source}
    while queue:
        path = queue.popleft(); current = path[-1]
        if current == destination: return path
        for nxt in sorted(graph[current]):
            if nxt not in seen: seen.add(nxt); queue.append(path + [nxt])
    return None


def candidate_paths(graph: dict[str, set[str]], source: str, destination: str) -> list[list[str]]:
    shortest = shortest_path(graph, source, destination)
    if shortest is None: return []
    limit = len(shortest) + 4
    queue = deque([[source]]); paths = []
    while queue and len(paths) < 80:
        path = queue.popleft()
        if len(path) > limit: continue
        if path[-1] == destination:
            paths.append(path); continue
        for nxt in sorted(graph[path[-1]]):
            if nxt not in path: queue.append(path + [nxt])
    return paths


def transfer(cells: list[dict], source: str, destination: str) -> None:
    lookup = {(cell["q"], cell["r"]): cell for cell in cells}
    source_nodes = {(cell["q"], cell["r"]) for cell in cells if cell["provinceId"] == source}
    destination_nodes = [(cell["q"], cell["r"]) for cell in cells if cell["provinceId"] == destination]
    center_q = sum(q for q, _ in destination_nodes) / len(destination_nodes); center_r = sum(r for _, r in destination_nodes) / len(destination_nodes)
    candidates = []
    for q, r in source_nodes:
        if any(lookup.get((q + dq, r + dr), {}).get("provinceId") == destination for dq, dr in NEIGHBORS) and connected(source_nodes - {(q, r)}): candidates.append((q, r))
    if not candidates: raise ValueError(f"No connected transfer from {source} to {destination}")
    node = min(candidates, key=lambda point: ((point[0] - center_q) ** 2 + (point[1] - center_r) ** 2, point))
    lookup[node]["provinceId"] = destination; lookup[node]["regionId"] = REGION_BY_PROVINCE[destination]


def adapt_layout(base: list[dict], targets: dict[str, int]) -> list[dict]:
    clean_base = [{key: value for key, value in cell.items() if key in {"q", "r", "provinceId", "regionId"}} for cell in base]
    for restart in range(120):
        cells = [dict(cell) for cell in clean_base]; rng = random.Random(f"layout-{restart}-{tuple(targets.values())}")
        for _ in range(350):
            counts = Counter(cell["provinceId"] for cell in cells)
            deficits = [pid for pid in sorted(targets) if counts[pid] < targets[pid]]
            if not deficits: return cells
            surpluses = [pid for pid in sorted(targets) if counts[pid] > targets[pid]]; graph = province_graph(cells); attempts = []
            for destination in deficits:
                for source in surpluses:
                    for path in candidate_paths(graph, source, destination):
                        attempts.append((len(path) + rng.random() * (0 if restart == 0 else 2.5), path))
            moved = False
            for _, path in sorted(attempts, key=lambda item: item[0]):
                candidate = [dict(cell) for cell in cells]
                try:
                    for source, destination in zip(path, path[1:]): transfer(candidate, source, destination)
                except ValueError: continue
                cells = candidate; moved = True; break
            if not moved: break
    raise ValueError("Could not adapt the reviewed layout after deterministic search")


def connected_piece_candidates(remaining: set[tuple[int, int]], size: int, seed_value: str):
    if size == len(remaining): return [set(remaining)]
    candidates, signatures = [], set()
    def keep(piece):
        signature = tuple(sorted(piece))
        if signature not in signatures and connected(piece) and connected(remaining - piece): signatures.add(signature); candidates.append(piece)
    if len(remaining) <= 16:
        import itertools
        for combination in itertools.combinations(sorted(remaining), size): keep(set(combination))
        return candidates
    directions = list(NEIGHBORS) + [(2, -1), (1, 1), (-1, 2), (-2, 1), (-1, -1), (1, -2)]
    seeds = sorted(remaining); rng = random.Random(seed_value)
    for attempt in range(1800):
        if attempt < len(seeds) * len(directions): direction, seed = directions[(attempt // len(seeds)) % len(directions)], seeds[attempt % len(seeds)]
        else: direction, seed = rng.choice(directions), rng.choice(seeds)
        piece = {seed}
        while len(piece) < size:
            frontier = {(q + dq, r + dr) for q, r in piece for dq, dr in NEIGHBORS if (q + dq, r + dr) in remaining - piece}
            if not frontier: break
            pick = min(frontier, key=lambda p: (-(p[0] * direction[0] + p[1] * direction[1]), p)) if attempt < len(seeds) * len(directions) else rng.choice(sorted(frontier))
            piece.add(pick)
        if len(piece) == size:
            keep(piece)
            if len(candidates) >= 260: break
    return candidates


def partition_connected(nodes: set[tuple[int, int]], counts: list[tuple[str, int]], seed: str):
    def solve(remaining, index):
        if index == len(counts) - 1: return {counts[index][0]: remaining} if connected(remaining) else None
        party_id, size = counts[index]
        for piece in connected_piece_candidates(remaining, size, f"{seed}-{index}-{party_id}"):
            rest = solve(remaining - piece, index + 1)
            if rest is not None: rest[party_id] = piece; return rest
        return None
    return solve(nodes, 0)


def party_counts(province_results: dict[str, list[dict]], province_id: str) -> list[tuple[str, int]]:
    counts = [(row["partyId"], row["seats"]) for row in province_results[province_id] if row["seats"]]
    return sorted(counts, key=lambda row: (row[1], row[0]))


def province_nodes(cells: list[dict], province_id: str) -> set[tuple[int, int]]:
    return {(cell["q"], cell["r"]) for cell in cells if cell["provinceId"] == province_id}


def reshape_for_partition(cells: list[dict], province_id: str, counts: list[tuple[str, int]], election_id: str) -> None:
    lookup = {(cell["q"], cell["r"]): cell for cell in cells}
    boundary_pairs = []
    for node in sorted(province_nodes(cells, province_id)):
        q, r = node
        for dq, dr in NEIGHBORS:
            other = lookup.get((q + dq, r + dr))
            if other and other["provinceId"] != province_id: boundary_pairs.append((lookup[node], other))
    rng = random.Random(f"reshape-{election_id}-{province_id}"); rng.shuffle(boundary_pairs)
    for own, other in boundary_pairs:
        other_id = other["provinceId"]
        own["provinceId"], other["provinceId"] = other_id, province_id
        own["regionId"], other["regionId"] = REGION_BY_PROVINCE[other_id], REGION_BY_PROVINCE[province_id]
        valid_shapes = connected(province_nodes(cells, province_id)) and connected(province_nodes(cells, other_id))
        pieces = partition_connected(province_nodes(cells, province_id), counts, f"{election_id}-{province_id}-reshape") if valid_shapes else None
        if pieces is not None: return
        own["provinceId"], other["provinceId"] = province_id, other_id
        own["regionId"], other["regionId"] = REGION_BY_PROVINCE[province_id], REGION_BY_PROVINCE[other_id]
    raise ValueError(f"Could not reshape {election_id}/{province_id} for connected party blocks {counts}")


def assign_parties(cells: list[dict], province_results: dict[str, list[dict]], election_id: str) -> list[dict]:
    for _ in range(80):
        failing = None
        for province_id in sorted(province_results):
            counts = party_counts(province_results, province_id)
            if partition_connected(province_nodes(cells, province_id), counts, f"{election_id}-{province_id}") is None:
                failing = (province_id, counts); break
        if failing is None: break
        reshape_for_partition(cells, failing[0], failing[1], election_id)
    else:
        raise ValueError(f"Could not make every province partitionable for {election_id}")
    by_province = defaultdict(list)
    for cell in cells: by_province[cell["provinceId"]].append(cell)
    output = []
    for province_id, province_cells in by_province.items():
        counts = party_counts(province_results, province_id)
        nodes = {(cell["q"], cell["r"]) for cell in province_cells}; pieces = partition_connected(nodes, counts, f"{election_id}-{province_id}")
        if pieces is None: raise ValueError(f"Could not partition {election_id}/{province_id}: {counts}")
        assigned = {node: party_id for party_id, piece in pieces.items() for node in piece}
        for cell in province_cells:
            node = (cell["q"], cell["r"]); output.append({"id": f"{election_id}-{province_id}-{cell['q']}-{cell['r']}", **cell, "partyId": assigned[node]})
    return sorted(output, key=lambda cell: (cell["r"], cell["q"]))


def result_rows(grouped: dict[str, dict], valid: int) -> list[dict]:
    rows = [{"partyId": party_id, "votes": int(values["votes"]), "share": round(values["votes"] / valid * 100, 2) if valid else 0, "seats": int(values["seats"])} for party_id, values in grouped.items() if values["votes"] or values["seats"]]
    return sorted(rows, key=lambda row: (-row["seats"], -row["votes"], row["partyId"]))


def aggregate_stats(stats: list[dict]) -> dict:
    keys = ("electors", "voters", "valid", "partyVotes", "blank", "invalid"); output = {key: sum(item[key] for item in stats) for key in keys}
    output["turnout"] = round(output["voters"] / output["electors"] * 100, 2) if output["electors"] else 0
    return output


def aggregate_results(provinces: list[dict], province_ids: list[str]) -> dict:
    selected = [province for province in provinces if province["id"] in province_ids]; stats = aggregate_stats([province["stats"] for province in selected]); grouped = defaultdict(lambda: {"votes": 0, "seats": 0})
    for province in selected:
        for row in province["results"]:
            grouped[row["partyId"]]["votes"] += row["votes"]; grouped[row["partyId"]]["seats"] += row["seats"]
    return {"stats": stats, "results": result_rows(grouped, stats["valid"])}


def build_election(frame: pd.DataFrame, election_id: str, label: dict) -> tuple[dict, dict[str, int]]:
    province_columns = list(frame.columns[4:56]); province_names = {f"{int(column.split(' - ', 1)[0]):02d}": column.split(" - ", 1)[1] for column in province_columns}
    metric_rows = {name: frame.loc[frame["Descripción"] == name].iloc[0] for name in ("Electores", "Votantes", "Votos válidos", "Votos nulos", "Votos en blanco", "Votos a candidaturas")}
    grouped = {pid: defaultdict(lambda: {"votes": 0, "seats": 0}) for pid in province_names}; aliases = defaultdict(set); pattern = re.compile(r"^(Votos|Escaños) \((.*)\)$")
    for row in frame.itertuples(index=False):
        match = pattern.match(str(row[3]))
        if not match: continue
        metric, raw_name = match.groups(); party_id = party_family(raw_name, election_id); aliases[party_id].add(raw_name)
        for offset, column in enumerate(province_columns, start=4):
            value = row[offset]
            if pd.isna(value) or not value: continue
            pid = f"{int(column.split(' - ', 1)[0]):02d}"; grouped[pid][party_id]["votes" if metric == "Votos" else "seats"] += int(value)
    provinces = []
    for pid, name in province_names.items():
        column = next(column for column in province_columns if column.startswith(f"{int(pid)} - "))
        stats = {"electors": int(metric_rows["Electores"][column]), "voters": int(metric_rows["Votantes"][column]), "valid": int(metric_rows["Votos válidos"][column]), "partyVotes": int(metric_rows["Votos a candidaturas"][column]), "blank": int(metric_rows["Votos en blanco"][column]), "invalid": int(metric_rows["Votos nulos"][column])}
        stats["turnout"] = round(stats["voters"] / stats["electors"] * 100, 2) if stats["electors"] else 0
        provinces.append({"id": pid, "regionId": REGION_BY_PROVINCE[pid], "name": {"en": name, "es": name}, "stats": stats, "results": result_rows(grouped[pid], stats["valid"])})
    regions = []
    for region_id in sorted(set(REGION_BY_PROVINCE.values())):
        province_ids = sorted(pid for pid, rid in REGION_BY_PROVINCE.items() if rid == region_id); regions.append({"id": region_id, "name": {"en": REGION_NAMES_EN[region_id], "es": REGION_NAMES_ES[region_id]}, "provinceIds": province_ids, **aggregate_results(provinces, province_ids)})
    national = aggregate_results(provinces, sorted(province_names)); winning = {row["partyId"] for row in national["results"] if row["seats"]}; party_ids = {row["partyId"] for province in provinces for row in province["results"]}
    parties = [party_meta(party_id, aliases[party_id]) for party_id in party_ids]; parties.sort(key=lambda party: (party["id"] not in winning, -next((row["seats"] for row in national["results"] if row["partyId"] == party["id"]), 0), party["short"]))
    discrepancy = sum(row["votes"] for row in national["results"]) - national["stats"]["partyVotes"]
    transformations = ["Province rows and all candidacies read from the Ministry's consolidated Congress workbook", "Candidacy aliases grouped only within documented party families", "Vote shares calculated over valid ballots, including blank ballots", "Autonomous-community and national totals derived from province rows using present-day regional groupings", "Seat allocations retained from the Ministry's definitive province rows"]
    if discrepancy: transformations.append(f"Source workbook candidacy rows differ from its party-vote summary by {discrepancy:+d} votes nationally; both published values are retained")
    election = {"id": election_id, "date": election_id, "label": label, "parties": parties, "national": national, "regions": regions, "provinces": provinces, "provenance": {"resultPublisher": "Ministerio del Interior — Infoelectoral", "resultUrl": SOURCE_URL, "finalStatus": "Definitive results including CERA where reported", "retrieved": "2026-09-04", "transformations": transformations}}
    return election, {province["id"]: sum(row["seats"] for row in province["results"]) for province in provinces}


def build(args) -> None:
    manifest = json.loads(args.manifest.read_text(encoding="utf-8")); workbook = pd.read_excel(args.congress_xlsx, sheet_name="Congreso", header=3); workbook["Fecha"] = pd.to_datetime(workbook["Fecha"]).dt.strftime("%Y-%m-%d")
    workbook_dates, expected_dates = set(workbook["Fecha"]), {item["id"] for item in manifest}
    if workbook_dates != expected_dates: raise ValueError(f"Workbook dates differ from manifest: {sorted(workbook_dates ^ expected_dates)}")
    province_source = json.loads(args.provinces.read_text(encoding="utf-8")); layout_cache: dict[tuple[int, ...], dict] = {}
    for item in reversed(manifest):
        election_id = item["id"]
        if election_id in CURRENT_ELECTIONS:
            if not (args.output_dir / f"{election_id}.json").exists(): raise FileNotFoundError(f"Missing reviewed payload for {election_id}")
            continue
        output = args.output_dir / f"{election_id}.json"; layout_path = args.layout_dir / f"province-layout-{election_id}.json"
        if output.exists() and layout_path.exists() and not args.force:
            print(f"Kept existing {output}")
            continue
        election, seat_counts = build_election(workbook[workbook["Fecha"] == election_id], election_id, item["label"])
        if sum(seat_counts.values()) != 350 or set(seat_counts) != set(REGION_BY_PROVINCE): raise ValueError(f"Invalid constituency allocation for {election_id}")
        fingerprint = tuple(seat_counts[pid] for pid in sorted(seat_counts)); layout_asset = json.loads(layout_path.read_text(encoding="utf-8")) if layout_path.exists() else layout_cache.get(fingerprint)
        if layout_asset is None: layout_asset = generate_layout(province_source, seat_counts, REGION_BY_PROVINCE); layout_cache[fingerprint] = layout_asset
        layout_path.parent.mkdir(parents=True, exist_ok=True); layout_path.write_text(json.dumps(layout_asset, ensure_ascii=False, separators=(",", ":")), encoding="utf-8")
        province_results = {province["id"]: province["results"] for province in election["provinces"]}; cells = assign_parties([dict(cell) for cell in layout_asset["cells"]], province_results, election_id)
        payload = {"schemaVersion": 1, "election": election, "layout": {"electionId": election_id, "cells": cells}}; args.output_dir.mkdir(parents=True, exist_ok=True); output.write_text(json.dumps(payload, ensure_ascii=False, separators=(",", ":")), encoding="utf-8"); print(f"Wrote {output} ({output.stat().st_size:,} bytes)")


def main() -> None:
    parser = argparse.ArgumentParser(); parser.add_argument("--congress-xlsx", type=Path, required=True); parser.add_argument("--provinces", type=Path, required=True); parser.add_argument("--manifest", type=Path, default=Path("src/data/election-manifest.json")); parser.add_argument("--layout-dir", type=Path, default=Path("data/layouts")); parser.add_argument("--output-dir", type=Path, default=Path("public/data/elections")); parser.add_argument("--force", action="store_true"); build(parser.parse_args())


if __name__ == "__main__": main()
